config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'welcome#about'
  root 'welcome#index'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :wikis

  resources :charges, only: [:new, :create]
  resources :downgrade, only: [:new, :create]
  post 'downgrade/create'
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  
  after_initialize :initialize_role
  
  private
  
  def initialize_role
    self.private = false if self.private.nil?
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    if current_user.present?
      collaborators = []
      @wiki.collaborators.each do |collaborator|
        collaborators << collaborator.email
      end
      unless (@wiki.private == false) || @wiki.user == current_user || collaborators.include?(current_user.email) || current_user.admin?
        flash[:alert] = "You are not authorized to view this wiki."
        redirect_to new_charge_path
      end
    else
      flash[:alert] = "You are not authorized to view this wiki."
      redirect_to new_user_registration_path
    end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end
  
  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    
    if @wiki.save
      @wiki.collaborators = Collaborator.update_collaborators(params[:wiki][:collaborators])
      flash[:notice] = "Your wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again later."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    
    if @wiki.save && (@wiki.user == current_user || current_user.admin?)
      @wiki.collaborators = Collaborator.update_collaborators(params[:wiki][:collaborators])
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    elsif @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
  
end

app/helpers/wikis_helper.rb
module WikisHelper
    def user_is_authorized_to_create?
        current_user && (current_user.admin? || current_user.premium?)
    end
    
    def user_is_authorized_to_update?
        current_user
    end
    
    def user_is_authorized_to_delete?
        current_user && (current_user == @wiki.user || current_user.admin?)
    end
    
    def markdown(text)
        extensions = [:tables, :fenced_code_blocks, :autolink, :strikethrough, :underline, :highlight, :quote, :footnotes]
        Markdown.new(text, *extensions).to_html.html_safe
    end

end

app/views/wikis/edit.html.erb
<% if user_is_authorized_to_update? %>
    <h1>Edit Wiki</h1>

    <div class="row">
        <div class="col-md-4">
            <p>Wiki rules</p>
            <ul>
                <li>Don't be a jerk.</li>
                <li>Make a wiki anyone can edit!</li>
            </ul>
        </div>
        <div class="col-md-8">
            <%= form_for @wiki do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
                </div>
                <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
                </div>
                <% if user_is_authorized_to_delete? %>
                    <div class="form-group">
                        <%= f.label :private, class: 'checkbox' do %>
                            <%= f.check_box :private %> Private wiki
                        <% end %>
                    </div>
                    <div class="form-group">
                        <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
                    </div>
                <% end %>
                <div class="form-group">
                    <%= f.submit "Save", class: 'btn btn-success' %>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<% if user_is_authorized_to_create? %>
    <div class="row">
        <div class="col-md-4">
            <%= link_to "Make a New Wiki", new_wiki_path, class: 'btn btn-success' %>
        </div>
    </div>
<% end %>

<% @wikis.each do |wiki| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= link_to wiki.title, wiki %>
            </h4>
        </div>
    </div>
<% end %>

app/views/wikis/new.html.erb
<% if user_is_authorized_to_create? %>
    <h1>New Wiki</h1>
    <div class="row">
        <div class="col-md-4">
            <p>Wiki rules</p>
            <ul>
                <li>Don't be a jerk.</li>
                <li>Make a wiki anyone can edit!</li>
            </ul>
        </div>
        <div class="col-md-8">
            <%= form_for @wiki do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
                </div>
                <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
                </div>
                <div class="form-group">
                    <%= f.label :private, class: 'checkbox' do %>
                        <%= f.check_box :private %> Private wiki
                    <% end %>
                </div>
                <div class="form-group">
                    <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
                </div>
                <div class="form-group">
                    <%= f.submit "Save", class: 'btn btn-success' %>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
    <div class="col-md-8">
        <p><%= markdown(@wiki.body) %></p>
        <p>Created by <%= @wiki.user.email %></p>
        <p>Collaborators:
            <% unless @wiki.collaborators.empty? %>
                <% @wiki.collaborators.each do |collaborator| %>
                    <p><%= collaborator.email %></p>
                <% end %>
            <% end %></p>
    </div>
    <div class="col-md-4">
        <% if user_is_authorized_to_update? %>
            <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <% end %>
        <%if user_is_authorized_to_delete? %>
            <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
        <% end %>
    </div>
</div>